<?php
/**
 * 404 Error Handler
 * Serves the static 404.html file generated by the CMS
 * This file is called by Apache's ErrorDocument directive
 */

// Set 404 status code
http_response_code(404);

// Path to the generated 404.html file (in root directory, same level as catalogue folder)
$errorPage = __DIR__ . '/../404.html';

if (file_exists($errorPage)) {
    // Set proper content type
    header('Content-Type: text/html; charset=UTF-8');
    // Serve the static HTML file
    readfile($errorPage);
    exit;
}

// Fallback if 404.html doesn't exist (shouldn't happen if CMS is set up correctly)
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 - Page Not Found</title>
</head>
<body>
    <h1>404 - Page Not Found</h1>
    <p>Sorry, the page you are looking for could not be found.</p>
    <a href="/">Go to Homepage</a>
</body>
</html>

